// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATe2mx3e3OVUQpSUGPmheQKqc96lKgfaA',
    appId: '1:841894549616:web:08d572196baab8e95ebcb5',
    messagingSenderId: '841894549616',
    projectId: 'we-chat-59ee9',
    authDomain: 'we-chat-59ee9.firebaseapp.com',
    storageBucket: 'we-chat-59ee9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv6DY8VAJFUwwcvj9hM7LbR4gR9aP2LFY',
    appId: '1:841894549616:android:8b6c2d8bb98ca85e5ebcb5',
    messagingSenderId: '841894549616',
    projectId: 'we-chat-59ee9',
    storageBucket: 'we-chat-59ee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNc97TeccigVw5JZkikeB0HAnRpwVWUiQ',
    appId: '1:841894549616:ios:71f7bcbd20804fc05ebcb5',
    messagingSenderId: '841894549616',
    projectId: 'we-chat-59ee9',
    storageBucket: 'we-chat-59ee9.appspot.com',
    androidClientId: '841894549616-1vmft2h5oc0ihv1aqf635nmkj8koll0r.apps.googleusercontent.com',
    iosClientId: '841894549616-mg4p51p0aantmj4hfv4bp3s5cpb3p06s.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNc97TeccigVw5JZkikeB0HAnRpwVWUiQ',
    appId: '1:841894549616:ios:71f7bcbd20804fc05ebcb5',
    messagingSenderId: '841894549616',
    projectId: 'we-chat-59ee9',
    storageBucket: 'we-chat-59ee9.appspot.com',
    androidClientId: '841894549616-1vmft2h5oc0ihv1aqf635nmkj8koll0r.apps.googleusercontent.com',
    iosClientId: '841894549616-mg4p51p0aantmj4hfv4bp3s5cpb3p06s.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
